# 1 Merged gene expression matrix and disease-free survival (DFS).

In [1]:
import numpy as np
import pandas as pd

# Load EDASeq normalized data.
allPatients = pd.read_csv('data/EDASeq_Normalized.csv')
allPatients

Unnamed: 0  TCGA-CV-A45W-01A-11R-A24Z-07  TCGA-CR-7388-01A-11R-2016-07  \
0           A1BG                             5                            10   
1           A1CF                             0                             1   
2          A2ML1                         28576                          9911   
3            A2M                         16551                         21816   
4         A4GALT                         27648                          2143   
...          ...                           ...                           ...   
17495       ZXDC                          2210                          2470   
17496     ZYG11A                           193                            31   
17497     ZYG11B                          1252                          2236   
17498        ZYX                         10052                         14475   
17499      ZZEF1                          2236                          3757   

       TCGA-CR-7379-01A-11R-2016-07  TCGA-CR-7393-01A-11R-2016-07  \
0                                 4                             7   
1                                 0                             0   
2                             20409                        121449   
3                             17747                         34953   
4                              7844                          2996   
...                             ...                           ...   
17495                          1332                          1384   
17496                            27                            27   
17497                          1448                          2241   
17498                         14846                         20793   
17499                          3657                          3996   

       TCGA-P3-A6T2-01A-11R-A34R-07  TCGA-CN-4737-01A-01R-1436-07  \
0                                11                             3   
1                                 4                             0   
2                              4051                         27739   
3                              4491                         21035   
4                              9398                          3412   
...                             ...                           ...   
17495                          1482                          3035   
17496                             6                            69   
17497                          1349                          1761   
17498                         19369                         12233   
17499                          2340                          4602   

       TCGA-CV-6960-01A-41R-2016-07  TCGA-T3-A92N-01A-11R-A39I-07  \
0                                27                             5   
1                                 0                             0   
2                             12192                          1764   
3                              2671                          3468   
4                              4115                          1568   
...                             ...                           ...   
17495                          1726                          2433   
17496                           530                            19   
17497                          2241                          1108   
17498                          7640                         22495   
17499                          2703                          1732   

       TCGA-CV-A6JZ-01A-11R-A31N-07  ...  TCGA-CV-6933-11A-01R-1915-07  \
0                                17  ...                             3   
1                                 0  ...                             2   
2                              1197  ...                           154   
3                             14889  ...                         29269   
4                               507  ...                          2324   
...                             ...  ...                           ...   
17495                          4249  ...

In [2]:
allPatients = allPatients.T
allPatients.columns = allPatients.iloc[0, :]
allPatients.insert(0, 'submitter', allPatients.index)
allPatients

Unnamed: 0                                       submitter  A1BG  A1CF  \
Unnamed: 0                                      Unnamed: 0  A1BG  A1CF   
TCGA-CV-A45W-01A-11R-A24Z-07  TCGA-CV-A45W-01A-11R-A24Z-07     5     0   
TCGA-CR-7388-01A-11R-2016-07  TCGA-CR-7388-01A-11R-2016-07    10     1   
TCGA-CR-7379-01A-11R-2016-07  TCGA-CR-7379-01A-11R-2016-07     4     0   
TCGA-CR-7393-01A-11R-2016-07  TCGA-CR-7393-01A-11R-2016-07     7     0   
...                                                    ...   ...   ...   
TCGA-CV-7438-11A-01R-2132-07  TCGA-CV-7438-11A-01R-2132-07     0     0   
TCGA-CV-7406-11A-01R-2081-07  TCGA-CV-7406-11A-01R-2081-07     1     0   
TCGA-CV-6943-11A-01R-1915-07  TCGA-CV-6943-11A-01R-1915-07     0     0   
TCGA-CV-7434-11A-01R-2132-07  TCGA-CV-7434-11A-01R-2132-07     3     0   
TCGA-CV-7437-11A-01R-2132-07  TCGA-CV-7437-11A-01R-2132-07     1     0   

Unnamed: 0                     A2ML1     A2M  A4GALT  A4GNT  AAAS  AACS  \
Unnamed: 0                     A2ML1     A2M  A4GALT  A4GNT  AAAS  AACS   
TCGA-CV-A45W-01A-11R-A24Z-07   28576   16551   27648      0  2154  2439   
TCGA-CR-7388-01A-11R-2016-07    9911   21816    2143      7  1471  2716   
TCGA-CR-7379-01A-11R-2016-07   20409   17747    7844      0  2406  4061   
TCGA-CR-7393-01A-11R-2016-07  121449   34953    2996      0  1182  3677   
...                              ...     ...     ...    ...   ...   ...   
TCGA-CV-7438-11A-01R-2132-07   95179    5868    2808      0  1643  4355   
TCGA-CV-7406-11A-01R-2081-07   31805   22216    2723      0  1204  2576   
TCGA-CV-6943-11A-01R-1915-07  130272    4598    2789      0  1500  5622   
TCGA-CV-7434-11A-01R-2132-07      36  194354    4043      0  1192  4491   
TCGA-CV-7437-11A-01R-2132-07  103654    2637    6137      1  1854  3653   

Unnamed: 0                    AADACL2  ...  ZW10  ZWILCH  ZWINT  ZXDA  ZXDB  \
Unnamed: 0                    AADACL2  ...  ZW10  ZWILCH  ZWINT  ZXDA  ZXDB   
TCGA-CV-A45W-01A-11R-A24Z-07      161  ...  1176    1554   1794   104   515   
TCGA-CR-7388-01A-11R-2016-07        7  ...   781     992   1796   129   801   
TCGA-CR-7379-01A-11R-2016-07        2  ...  1527    2404   2341   171   940   
TCGA-CR-7393-01A-11R-2016-07       25  ...  1198     643    709   208   975   
...                               ...  ...   ...     ...    ...   ...   ...   
TCGA-CV-7438-11A-01R-2132-07      220  ...  1537    1314   1560   109   506   
TCGA-CV-7406-11A-01R-2081-07        9  ...  1009     769    720   152   720   
TCGA-CV-6943-11A-01R-1915-07     1356  ...  1514    1126   1529   106   643   
TCGA-CV-7434-11A-01R-2132-07        2  ...   648     438    400   164   906   
TCGA-CV-7437-11A-01R-2132-07       73  ...  1654    1580   2539    94   468   

Unnamed: 0                    ZXDC  ZYG11A  ZYG11B    ZYX  ZZEF1  
Unnamed: 0                    ZXDC  ZYG11A  ZYG11B    ZYX  ZZEF1  
TCGA-CV-A45W-01A-11R-A24Z-07  2210     193    1252  10052   2236  
TCGA-CR-7388-01A-11R-2016-07  2470      31    2236  14475   3757  
TCGA-CR-7379-01A-11R-2016-07  1332      27    1448  14846   3657  
TCGA-CR-7393-01A-11R-2016-07  1384      27    2241  20793   3996  
...                            ...     ...     ...    ...    ...  
TCGA-CV-7438-11A-01R-2132-07  1572      92    1788  16694   3608  
TCGA-CV-7406-11A-01R-2081-07  1458      19    7850  17913   3216  
TCGA-CV-6943-11A-01R-1915-07  1440     115    1990  11556   3610  
TCGA-CV-7434-11A-01R-2132-07  1436       7    2488  18586   3415  
TCGA-CV-7437-11A-01R-2132-07  1789      76    1694  13443   4128  

[545 rows x 17501 columns]

In [3]:
# Process patient ID

allPatients.iloc[1:, 0] = allPatients.iloc[1:, 0].map(lambda x : '-'.join(x.split('-')[:4]))
allPatients

Unnamed: 0                           submitter  A1BG  A1CF   A2ML1     A2M  \
Unnamed: 0                          Unnamed: 0  A1BG  A1CF   A2ML1     A2M   
TCGA-CV-A45W-01A-11R-A24Z-07  TCGA-CV-A45W-01A     5     0   28576   16551   
TCGA-CR-7388-01A-11R-2016-07  TCGA-CR-7388-01A    10     1    9911   21816   
TCGA-CR-7379-01A-11R-2016-07  TCGA-CR-7379-01A     4     0   20409   17747   
TCGA-CR-7393-01A-11R-2016-07  TCGA-CR-7393-01A     7     0  121449   34953   
...                                        ...   ...   ...     ...     ...   
TCGA-CV-7438-11A-01R-2132-07  TCGA-CV-7438-11A     0     0   95179    5868   
TCGA-CV-7406-11A-01R-2081-07  TCGA-CV-7406-11A     1     0   31805   22216   
TCGA-CV-6943-11A-01R-1915-07  TCGA-CV-6943-11A     0     0  130272    4598   
TCGA-CV-7434-11A-01R-2132-07  TCGA-CV-7434-11A     3     0      36  194354   
TCGA-CV-7437-11A-01R-2132-07  TCGA-CV-7437-11A     1     0  103654    2637   

Unnamed: 0                    A4GALT  A4GNT  AAAS  AACS  AADACL2  ...  ZW10  \
Unnamed: 0                    A4GALT  A4GNT  AAAS  AACS  AADACL2  ...  ZW10   
TCGA-CV-A45W-01A-11R-A24Z-07   27648      0  2154  2439      161  ...  1176   
TCGA-CR-7388-01A-11R-2016-07    2143      7  1471  2716        7  ...   781   
TCGA-CR-7379-01A-11R-2016-07    7844      0  2406  4061        2  ...  1527   
TCGA-CR-7393-01A-11R-2016-07    2996      0  1182  3677       25  ...  1198   
...                              ...    ...   ...   ...      ...  ...   ...   
TCGA-CV-7438-11A-01R-2132-07    2808      0  1643  4355      220  ...  1537   
TCGA-CV-7406-11A-01R-2081-07    2723      0  1204  2576        9  ...  1009   
TCGA-CV-6943-11A-01R-1915-07    2789      0  1500  5622     1356  ...  1514   
TCGA-CV-7434-11A-01R-2132-07    4043      0  1192  4491        2  ...   648   
TCGA-CV-7437-11A-01R-2132-07    6137      1  1854  3653       73  ...  1654   

Unnamed: 0                    ZWILCH  ZWINT  ZXDA  ZXDB  ZXDC  ZYG11A  ZYG11B  \
Unnamed: 0                    ZWILCH  ZWINT  ZXDA  ZXDB  ZXDC  ZYG11A  ZYG11B   
TCGA-CV-A45W-01A-11R-A24Z-07    1554   1794   104   515  2210     193    1252   
TCGA-CR-7388-01A-11R-2016-07     992   1796   129   801  2470      31    2236   
TCGA-CR-7379-01A-11R-2016-07    2404   2341   171   940  1332      27    1448   
TCGA-CR-7393-01A-11R-2016-07     643    709   208   975  1384      27    2241   
...                              ...    ...   ...   ...   ...     ...     ...   
TCGA-CV-7438-11A-01R-2132-07    1314   1560   109   506  1572      92    1788   
TCGA-CV-7406-11A-01R-2081-07     769    720   152   720  1458      19    7850   
TCGA-CV-6943-11A-01R-1915-07    1126   1529   106   643  1440     115    1990   
TCGA-CV-7434-11A-01R-2132-07     438    400   164   906  1436       7    2488   
TCGA-CV-7437-11A-01R-2132-07    1580   2539    94   468  1789      76    1694   

Unnamed: 0                      ZYX  ZZEF1  
Unnamed: 0                      ZYX  ZZEF1  
TCGA-CV-A45W-01A-11R-A24Z-07  10052   2236  
TCGA-CR-7388-01A-11R-2016-07  14475   3757  
TCGA-CR-7379-01A-11R-2016-07  14846   3657  
TCGA-CR-7393-01A-11R-2016-07  20793   3996  
...                             ...    ...  
TCGA-CV-7438-11A-01R-2132-07  16694   3608  
TCGA-CV-7406-11A-01R-2081-07  17913   3216  
TCGA-CV-6943-11A-01R-1915-07  11556   3610  
TCGA-CV-7434-11A-01R-2132-07  18586   3415  
TCGA-CV-7437-11A-01R-2132-07  13443   4128  

[545 rows x 17501 columns]

In [4]:
# Read DFS data.

all_dfs = pd.read_excel("data/DFS.xlsx", usecols=[0, 4])
all_dfs = all_dfs.rename(columns={'submitter_id.samples': 'submitter'})
all_dfs

submitter  DFS_MONTHS
0    TCGA-QK-A8Z9-01B        6.73
1    TCGA-CR-7370-01A        3.45
2    TCGA-CV-7250-01A        3.65
3    TCGA-IQ-A61L-01A        5.12
4    TCGA-CV-6936-01A        5.16
..                ...         ...
196  TCGA-CN-4741-01A       71.22
197  TCGA-CN-5360-01A       71.25
198  TCGA-P3-A6T2-01A       75.49
199  TCGA-CR-5243-01A       84.17
200  TCGA-BB-4223-01A      105.81

[201 rows x 2 columns]

In [5]:
# Merge gene expression matrix and DFS according to patient ID.

myDataset = pd.merge(allPatients, all_dfs, how='inner', on='submitter')
myDataset

submitter A1BG A1CF   A2ML1    A2M A4GALT A4GNT  AAAS  AACS  \
0    TCGA-CR-7379-01A    4    0   20409  17747   7844     0  2406  4061   
1    TCGA-CR-7393-01A    7    0  121449  34953   2996     0  1182  3677   
2    TCGA-P3-A6T2-01A   11    4    4051   4491   9398     0  2046  1187   
3    TCGA-CN-4737-01A    3    0   27739  21035   3412     4  1818  3932   
4    TCGA-CV-5434-01A    5    1    2168  30339   3964     0  2050  1889   
..                ...  ...  ...     ...    ...    ...   ...   ...   ...   
180  TCGA-BA-6869-01A   20    0    8139   4718   7458     0  1613  3445   
181  TCGA-IQ-A61E-01A   12    0     232   5371   1683     8  1383  2690   
182  TCGA-CN-6023-01A    9    3     324  13188   9383     0  2233   767   
183  TCGA-MT-A51X-01A    4    1   27382   7999   2810     0   844  2786   
184  TCGA-QK-AA3K-01A   35    6       0  34797   2256     2  1853   382   

    AADACL2  ... ZWILCH ZWINT ZXDA  ZXDB  ZXDC ZYG11A ZYG11B    ZYX ZZEF1  \
0         2  ...   2404  2341  171   940  1332     27   1448  14846  3657   
1        25  ...    643   709  208   975  1384     27   2241  20793  3996   
2         4  ...   2569  5783  179   904  1482      6   1349  19369  2340   
3        98  ...   1314  1162  120   543  3035     69   1761  12233  4602   
4         3  ...   1430  1425  158   609  1419      5   1684  16838  3187   
..      ...  ...    ...   ...  ...   ...   ...    ...    ...    ...   ...   
180       1  ...   1464  1631  191   604  2024    126   1628   9353  2023   
181       0  ...   2157  4726   93   322  1758    271   1161  26357  2837   
182      23  ...   1671  3234  475  1185  1741     27   1603   8071  6268   
183     401  ...   1395  1553   55   591  1971     48   1057  14412  2061   
184       0  ...   1476  2335  117   422  1007    160   1391  16928  2493   

    DFS_MONTHS  
0        34.03  
1        32.62  
2        75.49  
3        20.53  
4        61.07  
..         ...  
180      21.16  
181      37.68  
182      52.04  
183       7.95  
184       8.31  

[185 rows x 17502 columns]

In [6]:
# Check the merged genes.

gene = myDataset.columns[1 : -1].to_numpy()
print(gene.shape)
print(gene)

(17500,)
['A1BG' 'A1CF' 'A2ML1' ... 'ZYG11B' 'ZYX' 'ZZEF1']


In [7]:
# Check the merged gene expression matrix and DFS.

data = myDataset.drop('submitter', axis = 1).to_numpy()

print(f'shape = {data.shape}')
print(data)

shape = (185, 17501)
[[4 0 20409 ... 14846 3657 34.03]
 [7 0 121449 ... 20793 3996 32.62]
 [11 4 4051 ... 19369 2340 75.49]
 ...
 [9 3 324 ... 8071 6268 52.04]
 [4 1 27382 ... 14412 2061 7.95]
 [35 6 0 ... 16928 2493 8.31]]


# 2 Use 12 months to divide radiation resistance (RR) and radiation sensitivity (RS).
+ Samples from 9-15 months have been manually removed.
+ RR: DFS is less than or equal to 12 months.
+ RS: DFS greater than 12 months.

In [8]:
data[:, -1:] = np.where(data[:, -1:] > 12, 0, 1)
print(data.shape)
print(data)

(185, 17501)
[[4 0 20409 ... 14846 3657 0]
 [7 0 121449 ... 20793 3996 0]
 [11 4 4051 ... 19369 2340 0]
 ...
 [9 3 324 ... 8071 6268 0]
 [4 1 27382 ... 14412 2061 1]
 [35 6 0 ... 16928 2493 1]]


In [9]:
feature = data[:, :-1].astype('float')
label = data[:, -1:].astype('int64')
print(feature.shape)
print(label.shape)

(185, 17500)
(185, 1)


# 3 Genes with an expression level of 0 were removed.

In [10]:
# For each gene, if there is a patient with an expression level of 0 for that gene, the gene is removed.

reservedList = []

for i in range(feature.shape[1]):
    if feature[:, i].tolist().count(0) == 0: # reserve
        reservedList.append(i)

feature = feature[:, reservedList]
gene = gene[reservedList]
print(feature.shape)
print(gene.shape)
print(gene)
print(feature)
np.save('data/geneAfterDiscard_0.npy', gene)

(185, 11959)
(11959,)
['A2M' 'A4GALT' 'AAAS' ... 'ZYG11B' 'ZYX' 'ZZEF1']
[[17747.  7844.  2406. ...  1448. 14846.  3657.]
 [34953.  2996.  1182. ...  2241. 20793.  3996.]
 [ 4491.  9398.  2046. ...  1349. 19369.  2340.]
 ...
 [13188.  9383.  2233. ...  1603.  8071.  6268.]
 [ 7999.  2810.   844. ...  1057. 14412.  2061.]
 [34797.  2256.  1853. ...  1391. 16928.  2493.]]


# 4 Oversampling of radiotherapy-resistant samples using the SMOTE algorithm.

In [11]:
from imblearn.over_sampling import SMOTE
from collections import Counter

print(f'before overstamp :{Counter(label.reshape(-1))}')

# Set random state for recurring.

overstamp = SMOTE(random_state=2022)
x, y = overstamp.fit_resample(feature, label)

print(f'after overstamp :{Counter(y)}')

y = y.reshape((-1, 1))
oversampled_data = np.append(x, y, axis = 1)

np.save("data/oversampled_data.npy", oversampled_data)

before overstamp :Counter({0: 148, 1: 37})
after overstamp :Counter({0: 148, 1: 148})
